package hooks

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/brizzai/fleet/internal/debuglog"
)

// openCodePluginName is fleet's status plugin file. fleet owns this file by name
// and only ever rewrites it — other plugins in the dir are left untouched.
const openCodePluginName = "fleet-status.ts"

// GetOpenCodeConfigDir returns OpenCode's config directory
// ($OPENCODE_CONFIG_DIR or ~/.config/opencode).
func GetOpenCodeConfigDir() string {
	if dir := os.Getenv("OPENCODE_CONFIG_DIR"); dir != "" {
		return dir
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(os.TempDir(), ".config", "opencode")
	}
	return filepath.Join(home, ".config", "opencode")
}

// openCodePluginTemplate is the generated status plugin. OpenCode auto-loads
// .ts files from <config>/plugin/ and calls the exported `event` hook for every
// bus event. The single %s is the JSON-quoted absolute fleet binary path.
//
// Status mapping (root session only — see the rootId latch below):
//
//	session.status{busy} -> session.busy        (running)
//	session.status{idle} / session.idle -> session.idle  (finished)
//	session.error        -> session.error        (error)
//	question.asked / permission.asked     -> permission.asked   (waiting)
//	question.replied / question.rejected /
//	  permission.replied                  -> permission.replied (running)
//
// Both event families are live in OpenCode 1.14.x and mean different things:
// question.* is the AskUserQuestion tool prompt, permission.* is a tool-permission
// prompt (the user's `permission: ask` config). Listening for only one is the
// stuck-at-running bug — add to these branches, never swap them.
//
// Root vs sub-agents: the session fleet launched goes busy before any sub-agent
// spawns, so the first event carrying a sessionID is always the root. The plugin
// latches that id and forwards only its events; sub-agent sessions (distinct ids)
// are ignored — no dependency on observing their session.created event, which the
// old exclude-set could miss and then falsely flip the root to Finished.
//
// Each is forwarded to `fleet hook-handler`, reusing the agent-neutral status
// pipeline. The call is synchronous (spawnSync): it blocks until the status file
// is written, which guarantees ordering (no stale status from out-of-order
// spawns) and — crucially — flushes the final status before OpenCode exits,
// rather than losing it to an unflushed async child. This matches how Claude and
// Codex hooks block synchronously. notify() early-returns when FLEET_INSTANCE_ID
// is unset, so a standalone (non-fleet) opencode session that loads this global
// plugin never forks fleet. Only a few events per turn are forwarded.
const openCodePluginTemplate = `// fleet status plugin — auto-generated by fleet; do not edit.
// Reports OpenCode session status to fleet via the fleet hook-handler.
import { spawnSync } from "node:child_process"

const FLEET_BIN = %s

function notify(event, sessionID) {
  if (!process.env.FLEET_INSTANCE_ID) return
  try {
    spawnSync(FLEET_BIN, ["hook-handler", "--fleet-hook"], {
      input: JSON.stringify({ hook_event_name: event, session_id: sessionID }),
      stdio: ["pipe", "ignore", "ignore"],
      env: process.env,
    })
  } catch (_e) {}
}

// rootId latches to the first session fleet's process drives. Its turn goes busy
// before any sub-agent spawns, so the first sessionID seen is the root; events
// from any other (sub-agent) session are then ignored.
let rootId = null

export const FleetStatus = async (_ctx) => ({
  event: async ({ event }) => {
    const type = event && event.type
    const props = (event && event.properties) || {}
    const sessionID = props.sessionID
    if (!sessionID) return
    if (rootId === null) rootId = sessionID
    if (sessionID !== rootId) return
    if (type === "session.status") {
      const st = props.status && props.status.type
      if (st === "busy") notify("session.busy", sessionID)
      else if (st === "idle") notify("session.idle", sessionID)
    } else if (type === "session.idle") {
      notify("session.idle", sessionID)
    } else if (type === "session.error") {
      notify("session.error", sessionID)
    } else if (type === "question.asked" || type === "permission.asked") {
      notify("permission.asked", sessionID)
    } else if (
      type === "question.replied" ||
      type === "question.rejected" ||
      type === "permission.replied"
    ) {
      notify("permission.replied", sessionID)
    }
  },
})
`

// InjectOpenCodePlugin writes (or refreshes) fleet's status plugin into
// OpenCode's global plugin dir (<configDir>/plugin/fleet-status.ts). Returns
// true if the file was written (changed). Idempotent: the resolved fleet binary
// path is baked in, so the file is rewritten only when fleet moves/upgrades.
//
// Unlike Claude/Codex (declarative hook JSON), OpenCode's hook mechanism is a
// JS/TS plugin, so fleet ships this generated file rather than merging JSON.
func InjectOpenCodePlugin(configDir string) (bool, error) {
	pluginDir := filepath.Join(configDir, "plugin")
	pluginPath := filepath.Join(pluginDir, openCodePluginName)

	binLiteral, err := json.Marshal(FleetBinaryPath())
	if err != nil {
		return false, fmt.Errorf("marshal fleet path: %w", err)
	}
	content := fmt.Sprintf(openCodePluginTemplate, binLiteral)

	if existing, err := os.ReadFile(pluginPath); err == nil {
		if bytes.Equal(bytes.TrimSpace(existing), bytes.TrimSpace([]byte(content))) {
			return false, nil
		}
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("read %s: %w", openCodePluginName, err)
	}

	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return false, fmt.Errorf("create plugin dir: %w", err)
	}
	tmpPath := pluginPath + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return false, fmt.Errorf("write %s.tmp: %w", openCodePluginName, err)
	}
	if err := os.Rename(tmpPath, pluginPath); err != nil {
		os.Remove(tmpPath)
		debuglog.Logger.Error("opencode plugin: rename failed", "err", err)
		return false, fmt.Errorf("rename %s: %w", openCodePluginName, err)
	}

	debuglog.Logger.Info("opencode status plugin injected", "path", pluginPath)
	return true, nil
}
